# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{elvallenato}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Maya"]
  s.date = %q{2009-11-23}
  s.description = %q{Gem to support el vallenato.com}
  s.email = %q{jmaya@lasamaria.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/elvallenato.rb",
     "lib/elvallenato/letra.rb",
     "lib/elvallenato/search.rb",
     "spec/elvallenato_spec.rb",
     "spec/fixtures/diomedes_search.htm",
     "spec/fixtures/siete_palabras.htm",
     "spec/letra_spec.rb",
     "spec/search_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem to support elvallentato.com}
  s.test_files = [
    "spec/elvallenato_spec.rb",
     "spec/letra_spec.rb",
     "spec/search_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end
